### ISSUE TITLE
Better support for existing compilers (that link files)

### ISSUE THREAD

**Issue by matthewmueller** [makojs/core#17]
This is really nebulous right now, so feel free to close. But one thing that might be nice is some sort of dependency aliasing. It's hard to explain so let me provide an example:

If you have an `index.jade` that has `extends layout.jade`. The jade compiler handles the linking itself. This is fine, but for recompiles, mako doesn't know about `layout.jade` because the jade compiler handled it. 

You can fairly easily get that dependency, but if you do `file.addDependency('layout.jade')` then mako actually tries to build it, when what you probably want is to signal to mako that it should rebuild the original `index.jade`.

You can find this sort of thing in a lot of different compilers (sass, stylus, etc.) I'm wondering if there's some sort of system we can introduce that allows us to add these files but have mako build off the original file. It might not make sense in core, but I'm finding it pretty difficult to do in a plugin as well and I think the easiest place to introduce this would be something like: `file.addDependency('layout.jade', { alias: true })`

**Comment by dominicbarnes** [comment]
I think this can actually be done with a plugin as-is, so I'll spitball a bit and we can talk more about it.

I would recommend adding the layout to the build, `file.addDependant('layout.jade');` but also attach a `layout: true` property. The `mako-jade` plugin can simply skip building those files. (and you can prune them from the tree during `postdependencies` so they won't be handled during assemble)

To address the issue of changing `layout.jade` and rebuilding `index.jade`, I would add a `preread` hook for `mako-jade` that marks all the dependencies for a file as dirty:

```js
mako.prewrite('jade', function (file) {
  // check is dirty
});
```

**Comment by dominicbarnes** [comment]
After thinking a bit more, adding the layout as a dependant (the reverse of a dependency) would mean it would not be traversed during analyze. I'm wondering if it makes sense to allow entry files to travel the opposite direction during that first pass. But then again, the layout is a dependency to the file itself... haha sorry for going back and forth on you like this. I still think it's possible, and would love to work to a solution either way.

**Comment by matthewmueller** [comment]
Haha no worries. It's a weird situation. Currently it cant be a dependant
because it wont build properly with jade, it cant be a dependency because
then mako doesn't know to rebuild the index.jade when layout changed.

It could go either way but I think it makes a little more sense as a
dependency, not a dependent. With some logic to tell mako to traverse up
(one or perhaps more layers).

**Comment by matthewmueller** [comment]
Just being a little more specific to avoid any confusion: it cant be a
dependant because jade compiler will try to recompile the layout and not
the index which wont work because the link is the other way "index extends
layout"

**Comment by matthewmueller** [comment]
thinking about this some more, i think it may make more sense to just walk the jade / sass / etc AST, pull out the deps, add them to mako and remove them in the code gen.

more work and slower, but cleaner and fits better within the existing system. i'll close for now. may revisit later if there's a clean approach to pulling this off.
