### ISSUE TITLE
pass in a file object or vinyl object to build directly

### ISSUE THREAD

**Issue by matthewmueller** [makojs/core#21]
One thing that would be nice is providing a `stdin` like functionality. I'm running into a case where I want to dynamically generate HTML to serve, but I want mako to build off those results (rather than write the file out first).

Something like:

```js
mako.build({
  path: "stdin.html",
  content: "some dynamically generated HTML",
  root: __dirname
})
```

**Comment by dominicbarnes** [comment]
Ah, yeah I wasn't really thinking about even supporting streams in core atm. However, if you can pass entries via vinyl objects, I think that'll suffice. (since you can prefill the `file.contents` using this method afaik)

**Comment by matthewmueller** [comment]
yah, i'm fine with that. I'm realizing there would also need to be some support from some of the plugins though, like read & stat, where they'll try and fetch the contents regardless of if `file.contents` or `file.stat` are already there.

**Comment by dominicbarnes** [comment]
@matthewmueller I think this is possible now, but I've not tried and would like your feedback before closing this issue.

As long as you don't add plugins like "stat", "buffer", etc for the "html" extension, you don't have to worry about things clobbering. Thus, you can add a pre-configured "stdin.html" or "server-generated.html" and it'll run through the flows as usual.

**Comment by dominicbarnes** [comment]
@matthewmueller: I've updated some of these modules upstream:
 - tree: now sets `file.contents = null` during reset
 - buffer: will skip running if `file.contents` is already defined

I _think_ this should be all you need to support passing in vinyl files that already have `contents` predefined and avoid clobbering. As such, I'll go ahead and close the issue, but please re-open if you run into any issues with this. (I'll do my best to write a short test-case for that entire scenario too)
