### ISSUE TITLE
dependant entries?

### ISSUE THREAD

**Issue by matthewmueller** [makojs/core#3]
One thing I've been wanting to do for a long time is be able to compile all the JS, CSS, and images from a single HTML/Jade page.

I can see two ways of doing this with mako:

1. Add new entries in a HTML/Jade plugin (`tree.addFile(dep, true)`) as you discover `script` or `link` tags
2. Add these assets as dependencies of the HTML/Jade plugin (`file.addDependency(dep)`) and then somehow treat them as entries with respect to building from that JS/CSS asset downward, even though the actual entry is the HTML/Jade plugin. 

#1 seems easier, but I don't really know if that would be the correct way to do things, since it kind of breaks the tree.

#2 is difficult because it's hard to know what the "relative entry" is, unless we mark it explicitly. 

I don't really know how this stuff works with watching/incremental builds, if i should try and keep the dependency tree intact as much as possible or if creating multiple entry points is fine.

---

To implement #1, mako would need to be able to update the entries list after each analysis step to see if anything new as been added.

To implement #2, mako would need to find another way to resolve this: https://github.com/makojs/css/blob/master/index.js#L89-L91 since the entry is an HTML file, not a CSS file.

**Comment by dominicbarnes** [comment]
As it stands currently, you'd need to build a plugin built for this purpose, but it can certainly be done.

I've contemplated making the js/css plugins only traverse upwards as long as the parent is also a js/css file. However, I haven't done this in practice yet, so I'm not sure exactly what implications that would have for the internals.

**Comment by matthewmueller** [comment]
Yah, I'm sort of just modifying the `mako-js` locally atm. 

Actually, I think traversing upwards would be fine, since the `file.type` should be resolved by then. I originally went down that road, but thought I might run into trouble if a coffeescript file required a JS file or something and I was looking for `.js`

**Comment by dominicbarnes** [comment]
Yeah, I'd definitely add tests for those types of scenarios, but I wouldn't mind adding such a feature to mako-js/css. (depending on the side-effects such a change, it might be worth adding behind an option)

**Comment by matthewmueller** [comment]
this is resolved in mako-tree!

**Comment by dominicbarnes** [comment]
this is resolved? (did you mean to close the other issue?)

**Comment by matthewmueller** [comment]
yah, not in core, but it can be done pretty easily in a plugin, which i think is the best place for it anyway

```js
    // check if the file is the topmost js file,
    // but it may not be an entry file
    // ex. html file includes a js file
    var isEntry = !dependants
      .filter(parent => {
        var file = tree.getFile(parent)
        return file.type === 'js'
      })
      .length;
```

**Comment by dominicbarnes** [comment]
Ok cool, yeah I was thinking about implementing this in mako-js/css. Feel free to open an issue on either of those plugins. :)
