### ISSUE TITLE
Rename analyze and assemble

### ISSUE THREAD

**Issue by dominicbarnes** [makojs/core#31]
Per our discussion in #24, I'd like to make the following renames:

 - analyze → parse
 - assemble → compile

Those names are much more commonly used by us developers for exactly these use-cases, so it doesn't make sense to try and "differentiate" on something trivial like a method name.

In addition to the core runner methods changing, a number of hooks and such will need to be renamed as well. (a breaking change for plugins I'm afraid) We're still not at 1.0 yet, so I'm not going to bother with deprecation notices.

**Comment by matthewmueller** [comment]
oh cool, you went with parse. thanks! :-D
