### ISSUE TITLE
Create a flowchart/diagram of a mako build

### ISSUE THREAD

**Issue by dominicbarnes** [makojs/core#32]
Based on our discussion in #24, a visual tool for understanding all the mako hooks and flows would be extremely beneficial to new users.

![example](https://cldup.com/Sc8FHxzYOE.jpeg)

**Comment by dominicbarnes** [comment]
I think I'm gonna spend some time tinkering around with Graphviz to make a few diagrams this weekend, that's the fastest way for me to get something up and running. (although I'm sure any graphic designer could make something far prettier by hand)

**Comment by matthewmueller** [comment]
ahh great idea :-) i had to do some graphviz work before, this website is pretty good for testing stuff out http://graphviz.herokuapp.com/, but the fastest way iteration-wise i found was to install an editor plugin to render and open the PDS

**Comment by dominicbarnes** [comment]
I added 2 new diagrams, showing each the parse and compile phases on [this page of the wiki](https://github.com/makojs/core/wiki/Hooks). I'm sure there are other ways of visualizing this flow, but I'll consider this issue resolved for now.
