### ISSUE TITLE
Switch to standard (or similar) for linting

### ISSUE THREAD

**Issue by dominicbarnes** [makojs/core#33]
Based on our discussion in #24, rather than relying on my personal ESLint config, it would encourage more community participation to adopt a more general tool like [standard](https://cldup.com/Sc8FHxzYOE.jpeg). (open to some of the other variants too)

**Comment by matthewmueller** [comment]
Tim Berner's Lee uses standard: https://twitter.com/feross/status/740592720230518784

Just sayin' ;-D
