### ISSUE TITLE
Get a proper logo

### ISSUE THREAD

**Issue by dominicbarnes** [makojs/core#35]
Based on our discussion in #24, I think I've pretty well settled on the name "mako" for this project. With that in mind, it'd be nice to get some sort of logo together, even if it's just a simple one. (anything beats those awful sprites that github generates lol)

**Comment by matthewmueller** [comment]
quick search:

![image](https://cloud.githubusercontent.com/assets/170299/16105789/6244af76-33b8-11e6-8f28-b865241bc787.png)

![image](https://cloud.githubusercontent.com/assets/170299/16105799/7af8d600-33b8-11e6-88d8-a32c84578ddf.png)

source: http://www.shutterstock.com/cat.mhtml?lang=en&language=en&ref_site=photo&search_source=search_form&version=llv1&anyorall=all&safesearch=1&use_local_boost=1&autocomplete_id=&search_tracking_id=0NRIU8QqLTKaNXNj4mt7SA&searchterm=cute%20shark&show_color_wheel=1&orient=&commercial_ok=&media_type=images&search_cat=&searchtermx=&photographer_name=&people_gender=&people_age=&people_ethnicity=&people_number=&color=&page=1&inline=79545766

**Comment by dominicbarnes** [comment]
Those look cool! I was thinking even more simple, would be cool to just have a "blueprint-y" fin. An optional touch would be a more wavy green (as an reference to the FFVII origin as well)

![mako/lifestream](http://www.gamecrate.com/wp-content/uploads/2014/09/ff7lifestream.jpg)

Or maybe somehow combine them, like a fin with waves that could just _look_ like water, but would be colored oddly, only as that slight reference.

**Comment by dominicbarnes** [comment]
Something like this is what I'm envisioning (just a quick whiteboard sketch)

![20160615_223247](https://cloud.githubusercontent.com/assets/160197/16106511/be99b9de-3349-11e6-9f53-72936670c698.jpg)

**Comment by matthewmueller** [comment]
love it! personally, i think it should be one metaphor or the other though, to me (the uninitiated) it looks like the shark is swimming in some pretty nasty water haha.

**Comment by dominicbarnes** [comment]
lol, fair enough. I'm no artist so I'll be content with anything at this point :P

**Comment by dominicbarnes** [comment]
This issue was moved to makojs/mako#1
