### ISSUE TITLE
Slowness creeping back in

### ISSUE THREAD

**Issue by dominicbarnes** [makojs/core#40]
I have a project of low/moderate complexity, and building the JS file is taking ~15s. Even with an output file that's ~1MB, I feel like that's way too slow.

I'm going to start adding even more timing logs in place to try and get to the bottom of this. Last time this occurred, it was an issue in the cycle detection, but maybe some other tree operation is now hogging up CPU cycles.

**Comment by dominicbarnes** [comment]
Well now... it looks like the slowness is because of sync stat calls being made by the [relative](https://github.com/jonschlinkert/relative) library. Ugh, that's what I get for not looking at the internals of a module before I include it. (but I'm so glad the built-in node profiler identified this really quickly for me!)

Since I'm only using `relative()` for logging purposes, I can easily swap it out for what I had before w/o any API changes. Going to do this right away.

**Comment by dominicbarnes** [comment]
Another big source of slowness is going to/from cache, my modest project has a >20MB cache file. I think I need to stop pretty-printing the JSON, and probably start gzipping too. (I'll create a separate issue for that)

**Comment by matthewmueller** [comment]
dang, well i'm glad this is a priority. this is what's driven me nuts using browserify and webpack.

**Comment by dominicbarnes** [comment]
All right, I've knocked off about 1/3 of the slowness. (update to all the latest patch versions)

**Comment by matthewmueller** [comment]
was leveldb a PITA to work with when you swapped that out in duo?

**Comment by dominicbarnes** [comment]
I'm trying to avoid it since it's a compiled module and I'm worried about Windows compat, so I'm going to try some other compression strategies before I pull in something like that. (I will do it if this cache turns out to consistently be the bottleneck)

**Comment by darsain** [comment]
Yeah always had issues with that in duo. I remember going several months just copy pasting one old build of leveldb to every new project, because building was failing on newer node version I wanted to use and leveldb was slow to adapt or something like that. Huge PITA!

**Comment by dominicbarnes** [comment]
Ok, I've sped up the cache a lot, but the "parse" phase is still taking much longer than expected. (7-8s on my example application) I've fixed all the issues I've identified here, so I still have some more profiling/digging to do.

**Comment by dominicbarnes** [comment]
When I run my build, the process seems to hang at various parts. It's possible that the GC is kicking in really hard, or maybe my `Queue` library is not really working right.

It's late, so I'm gonna call it a day for now. (will resume my efforts throughout this week)

**Comment by matthewmueller** [comment]
are you running babel? babel really causes things to lag

**Comment by dominicbarnes** [comment]
I am running babel, but that's definitely not the problem, as I can see what it's timing metrics look like. Plus, I'm specifically testing rebuilds where no files have changed. (ie: no files are "dirty")

**Comment by dominicbarnes** [comment]
The more profiling I do, the more I see the garbage collector running. I think I'm going to restore the default concurrency limit and look at mako-tree to see where I can save allocations. I've also seen my usage of `path.relative` taking a noticeable amount of time too, so I think I'm gonna create a mako-utils module with helpers for things like this, and start adding memoization and such to help out.

**Comment by dominicbarnes** [comment]
I've made some really great strides, and the build time is cut in half now. Now, the compile phase seems to be increasingly the bottleneck, so that will be what I investigate next.

**Comment by dominicbarnes** [comment]
I've changed core so that the compile phase only runs when files have changed, however this is breaking behavior in mako-serve which is disappointing. I may need to revert that change for now until I figure out a better strategy.

**Comment by dominicbarnes** [comment]
I'm going to close this, as I believe I've satisfied the spirit of the issue. I'm going to work on figuring out how best to optimize the compile phase, but will continue in #41.
