### ISSUE TITLE
Is it time for 1.0?

### ISSUE THREAD

**Issue by dominicbarnes** [makojs/core#43]
I don't have any more big outstanding issues I'd like to address atm, and I think the API is pretty well settled at this point. Does anyone have any thoughts here?

**Comment by darsain** [comment]
Still haven't gotten to using mako in any project yet, so no real world input here unfortunately -.- But assuming all in the current API works as it's supposed to, it seems pretty solid :)

**Comment by matthewmueller** [comment]
Yep the core is definitely stable! You've done a terrific job with this library  ✨ 

One thing I keep running up against is just wanting a single package with good defaults for common file types, a CLI, API and ability to serve some entries.

All of these things exist, but it's not in like a single downloadable thing.

More concretely:

- Common presets/bundles of best practices for file types, like JS, CSS, SVG, etc. (mako-browser includes CSS & JS)
- integrated CLI for serving and building files, with live-reload on every file type in the graph
- JS config over JSON config (rollup and webpack have sort of proved this out)

One suggestion for this is to have the **mako** npm packge be sort of this bundled builder thing like webpack or rollup or browserify, but mako-api or mako-core is the API, which is what's in this repo.

Not sure exactly where you stand on these issues, but I'm planning on just releasing a separate bundled version of all these things. I'd love to avoid duplicate work here, so maybe we can work together to start merging the stuff you like. I just need to keep stuff moving for contracts :-P

**Comment by dominicbarnes** [comment]
> Common presets/bundles of best practices for file types, like JS, CSS, SVG, etc. (whereas mako-browser includes CSS & JS)

I honestly thought that `mako-browser` was the bundle that accomplished this already. (it handles images like SVG too) Can you add more specifics around what you think is missing?

> integrated CLI for serving and building files

Are you suggested a combination of `mako-serve` and `mako-cli`? How would you feel about a `mako-toolkit` which does something like that?

> with live-reload on every file type in the graph

Yeah, I'd really like live-reload too (new issue: makojs/serve#29)

> JS config over JSON config

I'm open to this, but you can already do something like this:

```js
{
  "entries": [ "index.html" ],
  "plugins": [
    "./mako-plugins.js"
  ]
}
```

Which requires `mako-plugins.js` and attaches any plugins they export. (it should do the right thing if you either export an array or a function)

With that in mind, do you think something like that is still useful? Is it just because webpack/rollup do it? Personally, I find those JS configs to be way easy to spiral out of control in complexity, whereas I really want to put more complexity on plugin authors instead of users.

> One suggestion for this is to have the mako npm packge be sort of this bundled builder thing like webpack or rollup or browserify, but mako-api or mako-core is the API, which is what's in this repo.

I think this does make a lot of sense, maybe the `mako-toolkit` I proposed above can become `mako`, which includes a CLI and server baked in. It's nice that the current structure doesn't force anyone to adopt mako-cli/mako-serve if they wanted to roll their own solution. (though I guess bundling doesn't preclude that either)

**Comment by dominicbarnes** [comment]
I am reconsidering using the `@mako/` namespace. When I first started, searching on the npm website could not see scoped packages (even if they were public), but now that appears to have been fixed.

The most awkward thing about using scoped packages is that there no longer is the single `mako` entry-point. (which is one of those things that has been mentioned here several times already)

**Comment by dominicbarnes** [comment]
I just realized that I'm close to the 1 year anniversary of my first commit! (a6bae90e4fad824bbc0c900dbab89cc013d8f408)

I think I'm just going to pull the trigger and release 1.0 of everything sometime this weekend.

**Comment by dominicbarnes** [comment]
I'm going to close this issue, as I believe I've addressed the original questions and have created new issues for the things I want to tackle.
