### ISSUE TITLE
image optimization

### ISSUE THREAD

**Issue by dominicbarnes** [makojs/core#50]
I've always wanted to make image optimization easy to add to any front-end build, so I need a plugin for it now. There are tons of tools out there, so there are probably several plugins to be made. (then a bundle can be made for common collections)

**Comment by dominicbarnes** [comment]
I think the best choice for such a plugin is [imagemin](https://github.com/imagemin/imagemin), since it is able to operate directly on images as buffers in memory. In addition, the plugins cover all the tools I've ever heard of, and then some!

The tricky part is figuring out how to use plugins:
 - Option 1: bundle them all together with the mako plugin
    - con: more dependencies have to be installed implicitly (longer `npm install`, especially if any are native modules)
    - pro: less configuration for users
 - Option 2: require the user to install their own imagemin plugins
    - con: much more complexity for users
    - pro: far more lightweight
 - Option 3: use a mako plugin for each imagemin plugin
    - con: much higher maintenance cost
    - con: more complexity for users
    - pro: far more flexible

**Comment by darsain** [comment]
I'd pick option 2. What you call complexity I call more control for the user :)

**Comment by dominicbarnes** [comment]
Yeah, the more I think about it, that seems the best idea all around.

**Comment by dominicbarnes** [comment]
[mako-imagemin](https://github.com/makojs/imagemin) is now a thing!
