### ISSUE TITLE
relative paths don't work in parse/compile/build

### ISSUE THREAD

**Issue by darsain** [makojs/core#64]
So this:

```js
mako()
	.use(buffer(['css', ...css.images, ...css.fonts]))
	.use(css())
	.build('./foo.css')
	.then(build => {
		console.log(build.tree.getFiles());
	}, err => {
		console.log(err);
	});
```

Makes mako to prune all files in the tree. Passing an absolute path to `foo.css` works fine.

**Comment by dominicbarnes** [comment]
I'm debating where to normalize paths, as this could make the most sense in tree. Either way, the user should never have to care about absolute/relative paths. I think the fix makes sense in core just to transform a string like `./foo.css` as close as possible to being introduced into the system.

**Comment by darsain** [comment]
Vinyl 2.0 does path normalization already in all of its property setters. So just offload it to vinyl?

**Comment by dominicbarnes** [comment]
Hmmm... not sure why Vinyl didn't already catch this then. I'll have to look deeper into that part of mako-tree.

**Comment by darsain** [comment]
It doesn't resolve relative paths though, so maybe that is the issue?
