### ISSUE TITLE
compile should resolve/reject promise if tree is completely empty

### ISSUE THREAD

**Issue by darsain** [makojs/core#65]
Currently, when #64 happens, promise returned by `build()` just hangs with no resolution/rejection.

**Comment by dominicbarnes** [comment]
I need to figure out why this hangs at all, even an empty tree should have at least resolved. Either way, both parse and compile should probably throw in the event of an empty tree.

**Comment by darsain** [comment]
Well, not necessarily. What if user has some plugins that remove files, and sometimes they just remove all of them, and it's expected? :) But definitely at least resolve with empty tree.

**Comment by dominicbarnes** [comment]
That seems reasonable to me! It can be used to trigger a warning in mako-cli or something.
