### ISSUE TITLE
Incorrect directory separator in final files on windows

### ISSUE THREAD

**Issue by darsain** [makojs/core#69]
Not sure if this is tree, virtual file, or each individual plugin issue, so I'm posting it here :)

Mako's path resolution works properly, but doesn't account for the fact it was working with windows directory separators, but the resulting file needs UNIX ones.

For example, in my current project, this CSS:

```css
url('assets/font.ttf')
```

gets changed into this:

```css
url('..\assets\font.ttf')
```

Which throws 404s in the browser, since it sees that url as `....ssetsfont.ttf`.

**Comment by dominicbarnes** [comment]
This seems only applies to CSS, mind if I move the issue there? (if it affects JS too, it can be a separate issue)

**Comment by dominicbarnes** [comment]
This issue was moved to makojs/css#80
