### ISSUE TITLE
this.analyzing should be set to false if an error occurs

### ISSUE THREAD

**Issue by matthewmueller** [makojs/core#7]
right now if there's an error in the build, `this.analyzing` is still true.

**Comment by dominicbarnes** [comment]
ah, that's true. I'm guessing an error should just result in calling `file.dirty()` and then re-throwing.

**Comment by dominicbarnes** [comment]
I can imagine that this is a problem, so I intend to fix it. But I am curious as to what problems this caused you? I'm having difficulty writing up a test for this since I'm not sure what exactly to test for.

**Comment by matthewmueller** [comment]
sorry, i wrote this quickly last night before passing out haha. 

yep you're exactly right, it happens when there's an error a rebuild. basically:

```js
Watcher.on('watch', function (filepath) {
  var file = tree.getFile(filepath)

  file.dirty()
  
  mako
    .build(file.getEntries())
    .then(tree => console.log('compiled')
    .catch(e => console.error('oh no! if we save again, we're still going to be analyzing')
})
```
